version: 2.0.0.dev{build}
pull_requests:
  do_not_increment_build_number: true
init:
- cmd: >-
    ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%

    SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
environment:
  CHROMAPRINT_FPCALC_VERSION: 1.4.2
  DISCID_VERSION: 0.6.1
  matrix:
  - PYTHON: C:\Python36
    PYTHON_VERSION: 3.6.1
    PYTHON_ARCH: 32
  - PYTHON: C:\Python35
    PYTHON_VERSION: 3.5.3
    PYTHON_ARCH: 32
build: off
test_script:
- cmd: >-
    appveyor DownloadFile https://github.com/acoustid/chromaprint/releases/download/v%CHROMAPRINT_FPCALC_VERSION%/chromaprint-fpcalc-%CHROMAPRINT_FPCALC_VERSION%-windows-i686.zip -FileName fpcalc.zip

    7z x fpcalc.zip -y

    copy /Y chromaprint-fpcalc-%CHROMAPRINT_FPCALC_VERSION%-windows-i686\fpcalc.exe %PYTHON%

    appveyor DownloadFile http://ftp.musicbrainz.org/pub/musicbrainz/libdiscid/libdiscid-%DISCID_VERSION%-win32.zip -FileName libdiscid.zip

    7z x libdiscid.zip -y

    copy /Y libdiscid-%DISCID_VERSION%-win32\discid.dll %PYTHON%

    pip install -r requirements.txt

    python setup.py test -v
deploy: off
